apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: google-keep-clone
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: google-keep-clone
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: google-keep-clone
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
  namespace: google-keep-clone
