{{- if .Values.secrets.create.backend.databaseUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: {{ include "google-keep-clone.namespace" . }}
  labels: {{- include "google-keep-clone.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.create.backend.databaseUrl }}
{{- end }}
