apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: google-keep-clone
  namespace: {{ include "google-keep-clone.namespace" . }}
  labels: {{- include "google-keep-clone.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.{{ include "google-keep-clone.namespace" . }}.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://{{ .Values.ingress.host }}/oauth2/start?rd=$escaped_request_uri
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: google-keep-clone-oauth2
  namespace: {{ include "google-keep-clone.namespace" . }}
  labels: {{- include "google-keep-clone.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80
