{{- if or .Values.secrets.create.postgres.username .Values.secrets.create.postgres.password .Values.secrets.create.postgres.database }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ include "google-keep-clone.namespace" . }}
  labels: {{- include "google-keep-clone.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.secrets.create.postgres.username }}
  username: {{ .Values.secrets.create.postgres.username }}
{{- end }}
{{- if .Values.secrets.create.postgres.password }}
  password: {{ .Values.secrets.create.postgres.password }}
{{- end }}
{{- if .Values.secrets.create.postgres.database }}
  database: {{ .Values.secrets.create.postgres.database }}
{{- end }}
{{- end }}
